
LOCAL_STATIC_JAVA_LIBRARIES=
LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES=

for i in ./libs/*.jar
do
	BASENAME=`basename $i .jar`
	LOCAL_STATIC_JAVA_LIBRARIES="$LOCAL_STATIC_JAVA_LIBRARIES \t$BASENAME \\\\\n"
	LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES="$LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES $BASENAME:$i " 
done

	echo -e "LOCAL_STATIC_JAVA_LIBRARIES := $LOCAL_STATIC_JAVA_LIBRARIES"
	echo -e "LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES := $LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES"
